// Build step 0: pull the live catalog from the API into src/content/data/
// so the prerendered product, blog and project pages match what the team
// edits in /admin.
//
//   CONTENT_API_URL=https://api.circuitbay.in npm run build
//
// Without CONTENT_API_URL (local development) the committed data files are
// used as they are. If the API is set but unreachable, or returns an empty
// catalog, the build fails instead of publishing a broken site.
import { writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const base = process.env.CONTENT_API_URL?.replace(/\/$/, '')

if (!base) {
  console.log('pull-content: CONTENT_API_URL not set — building from the committed content in src/content/data/')
  process.exit(0)
}

// The API caches public reads (60–300 s). A per-build value in the query
// string gives every request a fresh cache key, so a "Publish" right after
// an edit never builds from stale content.
const buildId = Date.now().toString(36)

async function get(path) {
  const url = `${base}/api${path}${path.includes('?') ? '&' : '?'}build=${buildId}`
  const res = await fetch(url, { headers: { accept: 'application/json', 'cache-control': 'no-cache' } })
  if (!res.ok) throw new Error(`GET ${path} → HTTP ${res.status}`)
  return res.json()
}

// Follows the API's pagination until every item is fetched
async function all(path, key, limit) {
  const out = []
  for (let page = 1; page <= 200; page++) {
    const sep = path.includes('?') ? '&' : '?'
    const body = await get(`${path}${sep}limit=${limit}&page=${page}`)
    out.push(...body[key])
    if (page >= (body.pages ?? 1) || body[key].length < limit) break
  }
  return out
}

const pick = (o, keys) => Object.fromEntries(keys.filter((k) => o[k] !== undefined && o[k] !== null).map((k) => [k, o[k]]))

const PRODUCT_FIELDS = ['id', 'name', 'category', 'kit', 'level', 'price', 'stock', 'brand', 'type', 'badges', 'forWhat', 'build', 'inside', 'specs', 'images', 'datasheetUrl', 'hsnCode', 'gstRate', 'rating', 'reviews']
const ARTICLE_FIELDS = ['slug', 'title', 'seoTitle', 'category', 'excerpt', 'readTime', 'author', 'date', 'updated', 'featured', 'cover', 'parts', 'relatedProjects', 'body']
const PROJECT_FIELDS = ['id', 'title', 'blurb', 'description', 'tags', 'builder', 'category', 'image', 'link', 'featured']

const header = (what) =>
  `// ${what} — generated by scripts/pull-content.js from ${base} on ${new Date().toISOString()}.\n` +
  '// Do not edit by hand — edit content in /admin.\n'

function write(file, what, data) {
  writeFileSync(join(root, 'src/content/data', file), `${header(what)}export default ${JSON.stringify(data, null, 2)}\n`)
}

try {
  const [products, articleList, projectsRes] = await Promise.all([
    all('/products?category=all&sort=featured', 'products', 48),
    all('/articles', 'articles', 30),
    get('/projects?limit=50'),
  ])
  // List responses omit article bodies — fetch each article in full
  const articles = await Promise.all(articleList.map((a) => get(`/articles/${encodeURIComponent(a.slug)}`).then((r) => r.article)))
  const projects = projectsRes.projects

  if (products.length === 0) throw new Error('the API returned no products')

  write('products.js', 'Shop products', products.map((p) => pick(p, PRODUCT_FIELDS)))
  write('articles.js', 'Blog articles', articles.map((a) => pick(a, ARTICLE_FIELDS)))
  write('projects.js', 'Community projects', projects.map((p) => pick(p, PROJECT_FIELDS)))
  console.log(`pull-content: ${products.length} products, ${articles.length} articles, ${projects.length} projects from ${base}`)
} catch (err) {
  console.error(`pull-content: couldn't load content from ${base}: ${err.message}`)
  process.exit(1)
}
