// Builds seed/seed.sql from the frontend's draft content files, so the API
// starts with the same catalog, articles and projects the site shows.
// Idempotent (INSERT OR REPLACE) — safe to re-run. TODO_CLIENT: once the
// real catalog exists, manage products via /api/admin instead.
import { mkdirSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { products, shopCategories } from '../../src/content/shopData.js'
import { articles } from '../../src/content/blogData.js'
import { projects } from '../../src/content/siteContent.js'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const now = Date.now()

const lit = (v) => {
  if (v === null || v === undefined) return 'NULL'
  if (typeof v === 'number') return String(v)
  if (typeof v === 'boolean') return v ? '1' : '0'
  if (typeof v === 'object') v = JSON.stringify(v)
  return `'${String(v).replace(/'/g, "''")}'`
}
const insert = (table, row) =>
  `INSERT OR REPLACE INTO ${table} (${Object.keys(row).join(', ')}) VALUES (${Object.values(row).map(lit).join(', ')});`

const lines = ['-- Generated by scripts/build-seed.js — do not edit by hand.']

shopCategories.forEach((c, i) =>
  lines.push(insert('categories', { slug: c.slug, label: c.label, icon: c.icon, blurb: c.blurb, sort_order: i })),
)

for (const p of products) {
  lines.push(
    insert('products', {
      id: p.id,
      name: p.name,
      category: p.category,
      is_kit: Boolean(p.kit),
      level: p.level ?? null,
      price_paise: Math.round(p.price * 100),
      stock: p.stock ?? 0,
      brand: p.brand ?? null,
      type: p.type ?? null,
      badges: p.badges ?? [],
      for_what: p.forWhat ?? null,
      build: p.build ?? null,
      inside: p.inside ?? [],
      specs: p.specs ?? {},
      images: [],
      hsn_code: p.hsnCode ?? null, // TODO_CLIENT: HSN code per product
      gst_rate: p.gstRate ?? 18,
      rating: p.rating ?? 0,
      reviews_count: p.reviews ?? 0,
      active: true,
      created_at: now,
      updated_at: now,
    }),
  )
}

for (const a of articles) {
  lines.push(
    insert('articles', {
      slug: a.slug,
      title: a.title,
      seo_title: a.seoTitle ?? null,
      category: a.category,
      excerpt: a.excerpt,
      body: a.body ?? [],
      read_time: a.readTime ?? null,
      author: a.author ?? null,
      featured: Boolean(a.featured),
      parts: a.parts ?? [],
      related_projects: a.relatedProjects ?? [],
      status: a.draft ? 'draft' : 'published',
      published_at: Date.parse(a.date),
      created_at: now,
      updated_at: now,
    }),
  )
}

projects.forEach((p, i) =>
  lines.push(
    insert('projects', {
      id: p.id,
      title: p.title,
      blurb: p.blurb,
      tags: p.tags ?? [],
      builder: p.builder,
      category: p.category,
      featured: i === 0,
      status: 'published',
      created_at: now - i * 1000,
      updated_at: now,
    }),
  ),
)

mkdirSync(join(root, 'seed'), { recursive: true })
writeFileSync(join(root, 'seed', 'seed.sql'), lines.join('\n') + '\n')
console.log(`seed/seed.sql: ${shopCategories.length} categories, ${products.length} products, ${articles.length} articles, ${projects.length} projects`)
